//@ sourceMappingURL=config.map
// Generated by CoffeeScript 1.6.1
var Config;

Config = (function() {

  function Config(rawConfig) {
    this.timeout = 60000;
    this.apiVersion = '1';
    this.baseUrl = rawConfig.baseUrl;
    this.username = rawConfig.username;
    this.password = rawConfig.password;
    this.ssl = rawConfig.ssl;
  }

  return Config;

})();

exports.Config = Config;
