//@ sourceMappingURL=http.map
// Generated by CoffeeScript 1.6.1
var Buffer, Http, Util, exceptions, http, https, querystring, request;

http = require('http');

https = require('https');

request = require("request");

querystring = require('querystring');

Buffer = require('buffer').Buffer;



exceptions = require('./exceptions');

Util = require('./util').Util;

Http = (function() {

  function Http(config) {
    this.config = config;
  }

  Http.prototype["delete"] = function(url, callback) {
    return this.request('DELETE', url, null, callback);
  };

  Http.prototype.get = function(url, callback) {
    return this.request('GET', url, null, callback);
  };

  Http.prototype.post = function(url, body, callback) {
    return this.request('POST', url, body, callback);
  };

  Http.prototype.put = function(url, body, callback) {
    return this.request('PUT', url, body, callback);
  };

  Http.prototype.request = function(method, url, body, callback) {
    var options = { method: method,
      url: url,
      qs: body,
      timeout: this.config.timeout,
      headers:{
         'cache-control': 'no-cache'
      }
    };
    request(options, function (error, response, body) {
      if (error) return callback(error, null);
      return callback(null, body);
    });
  };

  return Http;

})();

exports.Http = Http;
