//@ sourceMappingURL=client_token_gateway.map
// Generated by CoffeeScript 1.6.1
var MoChargeRequestGateway, DEFAULT_VERSION, ErrorResponse, Util, deprecate, exceptions, querystring;
  


Util = require('./util').Util;

exceptions = require('./exceptions');

querystring = require('querystring');


DEFAULT_VERSION = 2;

MoChargeRequestGateway = (function(_super) {

  //__extends(MoChargeRequestGateway, _super);

  function MoChargeRequestGateway(gateway) {
    this.gateway = gateway;
    this.config = this.gateway.config;
  }

  MoChargeRequestGateway.prototype.send = function(params, callback) {
    var err, responseHandler;
    if (params == null) {
      params = {};
    }
    //params = Object.assign(params, {operation: 'pinrequest'});
    
    params = Object.assign(params, {username: this.config.username, password: this.config.password, operation: 'mocharge'});
    err = this.validateParams(params);
    if (err) return callback(err, null);
    responseHandler = this.responseHandler(callback);
    return this.gateway.http.post(this.config.baseUrl , params, responseHandler);
  };

  MoChargeRequestGateway.prototype.validateParams = function(params) {
    var options, invalidOptions = [];    
    options = ["username", "password", "operation", "msisdn", "pin"];
    for(var i = 0; i < options.length; i++)
    {
      if(!params[options[i]])
        invalidOptions.push(options[i]);
    }
    if(invalidOptions.length > 0)
      return exceptions.UnexpectedError("Invalid keys: " + invalidOptions.join(', '));
    else
      return null;
  };

  MoChargeRequestGateway.prototype.responseHandler = function(callback) {
    return function(err, response) {
      var responseObj = querystring.parse(response);
      if (err) 
        return callback(err, response);
      //validate response
      if(responseObj.resultcode === '0')
        return callback(null, responseObj);
      else
        return callback(new Error(responseObj.description? responseObj.description : response), null);
      
    };
  };
  
  return MoChargeRequestGateway;

})();
exports.MoChargeRequestGateway = MoChargeRequestGateway;
